### ISSUE TITLE
Finished MVP: User Auth

### ISSUE THREAD

**Issue by karapliu** [karapliu/pickle-app#6]
- [ ] Visitors can sign up, sign in, and sign out
- [ ] Visitors can use demo login 
- [ ] Styled splash page 
- [ ] Styled sign up and log in forms

Can't figure out how to have the lines not poke through the circles in the 1-2-3 on the home page.

**Comment by PedroKim** [comment]
- [ ] Splash
  - For footer, you can take out list of states.
  - For "Trusted around the world" update the list with items: github, linkedin, and angelist.
- [ ] Sign Up
  - Instead of displaying errors on the top, invalid fields should turn red like the actual signup.
  - Also, include tooltips hinting at what is wrong.
- [ ] Sign In
  - Match the error styling with an X to hide the error.
